[package]
name = "datasworn-rust-test"
version = "0.1.0"
edition = "2021"
publish = false

# Suppress warnings in generated code
[lints.rust]
dead_code = "allow"
non_snake_case = "allow"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
